Repository imjoy-team/imjoy-engine, pull requests merged in 2021-04, with the labels that each got.

#106 Add imjoy core implementation
  README.md
  imjoy/VERSION
  imjoy/__init__.py
  imjoy/__main__.py
  imjoy/core/__init__.py
  imjoy/core/auth.py
  imjoy/core/connection.py
  imjoy/core/interface.py
  imjoy/core/plugin.py
  imjoy/options.py
  imjoy/runner.py
  imjoy/server.py
  imjoy/socketio_server.py
  pylintrc
  requirements.txt
  requirements_test.txt
  setup.py
  tests/example_plugin.py
  tests/main_test.py
  tests/test_imjoy_engine_server.py
  tests/test_jupyter.py
Labels: documentation, enhancement

#129 Fix black formatting
  imjoy/options.py
  imjoy/runner.py
  imjoy/server.py
Labels: ci

#128 Add labels action
  .github/labels.yml
  .github/workflows/labeler.yml
Labels: ci, github_actions

#132 Add fastapi to requirements
  imjoy/VERSION
  requirements.txt
  setup.py
Labels: enhancement

#133 Fix root endpoint bug
  imjoy/VERSION
  imjoy/core/__init__.py
  imjoy/core/interface.py
  imjoy/runner.py
  imjoy/server.py
  requirements.txt
  setup.py
  tests/test_imjoy_engine_server.py
Labels: bug

#134 Fix interface update
  requirements.txt
  setup.py
  tests/test_imjoy_engine_server.py
Labels: bug

#135 Improve PR autolabeling
  .github/release-drafter.yml
Labels: ci

#136 Bump rpc version to 0.3.7 and remove unused utils files
  requirements.txt
  setup.py
  utils/ImJoyEngine.platypus
  utils/ImJoyEngine.ps1
  utils/ImJoyEngine.sh
  utils/LICENSE
  utils/Linux_Install.sh
  utils/OSX_Install.sh
  utils/README.txt
  utils/imjoy-plugin-example.ipynb
Labels: removal

#137 Fix plugin runner
  README.md
  imjoy/VERSION
  imjoy/runner.py
  tests/example_plugin.py
  tests/test_imjoy_engine_server.py
Labels: bug, documentation
